
- name: Retrieve incident info
  servicenow.itsm.incident_info:
    instance:
      host: "{{ servicenow_instance }}"
      username: "{{ servicenow_user }}"
      password: "{{ servicenow_password }}"
    # number: "{{ incident_number }}"
    sysparm_query: category=apstra_dc
  register: incident_info

# - name: Display incident info
#   debug:
#     var: incident_info

- name: copy incident to file
  local_action: 
    module: copy 
    content: "{{ incident_info }}"
    dest: ./tmp.json

- name: execute install script
  script: snow_anomalie_check.py
  args:
    executable: python3


# - name: unflattened list
#   debug:
#     msg: "{{ item.type }} {{ item.id }} {{ item.status }}"
#   loop:
#     "{{ lookup('file', 'to_create_data.data') }}"

- name: Create incidents
  servicenow.itsm.incident:
    instance:
      host: "{{ servicenow_instance }}"
      username: "{{ servicenow_user }}"
      password: "{{ servicenow_password }}"
    state: new
    caller: "{{ servicenow_user }}"
    short_description: "{{ item.type }} {{ item.id }} {{ item.status }}"
    description: "{{ item.type }} {{ item.id }} {{ item.status }}"
    impact: high
    urgency: high
  loop:
    "{{ lookup('file', 'to_create_data.data') }}"