- name: Execute custom module
  get_api_token:
    username: "{{ username }}"
    password: "{{ password }}"
    ip: "{{ ip }}"
    port: "{{ port }}"
  register: result
- name: Print result
  debug:
    var: result.token

- name: Get all blueprint information
  get_apstra_blueprints:
    blueprint_name: "{{ blueprint_name }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ip: "{{ ip }}"
    port: "{{ port }}"
  register: result
- name: Print result
  debug:
    var: result.blueprint_information.id, result.blueprint_information.design

- name: Get all blueprint anomalieinformation
  get_apstra_blueprint_anomalie:
    blueprint_id: "{{ blueprint_id }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ip: "{{ ip }}"
    port: "{{ port }}"
  register: anomalie_result

- local_action: 
    module: copy 
    content: "{{ anomalie_result }}"
    dest: anomalie_result.json

- name: Print result
  debug:
    var: anomalie_result
