- name: Execute custom module
  get_api_token:
    username: "{{ username }}"
    password: "{{ password }}"
    ip: "{{ ip }}"
    port: "{{ port }}"
  register: result
- name: Print result
  debug:
    var: result.token

- name: Get all blueprint information
  get_apstra_blueprints:
    blueprint_name: "{{ blueprint_name }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ip: "{{ ip }}"
    port: "{{ port }}"
  register: result
- name: Print result
  debug:
    var: result.blueprint_information.id, result.blueprint_information.design
