
- name: Run my role
  hosts: localhost
  gather_facts: yes
  roles:
    - create_apstra_tenant
  vars:
    apstra_username: "admin"
    apstra_password: "admin"
    apstra_address: "172.30.54.20"
    apstra_port: 443
    validate_certs: false
