- name: Run my role
  hosts: localhost
  gather_facts: no

  pre-tasks:
    - name: Install pip package
      pip:
        name: "{{ package_name }}"
        state: present 
  vars:
    package_name: "apstra-api-python"

  roles:
    - getBlueprintInfo
  vars:
    username: "admin"
    password: "RapidKrill3$"
    ip: "13.38.32.96"
    port: 22259
    blueprint_name: "apstra-pod1"
