- name: Run my role
  hosts: localhost
  gather_facts: no

  pre_tasks:
    - name: Install pip package
      pip:
        name: "{{ package_name }}"
        state: present
  roles:
    - getBlueprintInfo
  vars:
    username: "admin"
    password: "admin"
    ip: "172.30.92.20"
    port: 443
    blueprint_name: "Adam_Jarvis_Multivendor_SE_Demo_2ce34943cd0f - evpn-sonicvs_nxosv-virtual"
    package_name: "apstra-api-python"
