- name: Extract leaf IDs from JSON array
  hosts: localhost
  vars:
    leaf_ids: {}
    json_data: '{
        "count": 4,
        "items": [
            {
                "leaf": {
                    "deploy_mode": null,
                    "external": false,
                    "group_label": "tor",
                    "hostname": "single-tor-002-leaf1",
                    "id": "TfeUda5cObjbvzdetDM",
                    "label": "_single_tor_002_leaf1",
                    "management_level": "full_control",
                    "port_channel_id_max": null,
                    "port_channel_id_min": null,
                    "position_data": null,
                    "property_set": null,
                    "role": "leaf",
                    "system_id": null,
                    "system_type": "switch",
                    "tags": null,
                    "type": "system"
                }
            },
            {
                "leaf": {
                    "deploy_mode": null,
                    "external": false,
                    "group_label": "esi_tor",
                    "hostname": "esi-tor-001-leaf1",
                    "id": "W4UWHs_3sZuergyBiuE",
                    "label": "_esi_tor_001_leaf1",
                    "management_level": "full_control",
                    "port_channel_id_max": null,
                    "port_channel_id_min": null,
                    "position_data": null,
                    "property_set": null,
                    "role": "leaf",
                    "system_id": null,
                    "system_type": "switch",
                    "tags": null,
                    "type": "system"
                }
            },
            {
                "leaf": {
                    "deploy_mode": null,
                    "external": false,
                    "group_label": "tor",
                    "hostname": "single-tor-001-leaf1",
                    "id": "UB4XaGmBDVcy_9MmG8c",
                    "label": "_single_tor_001_leaf1",
                    "management_level": "full_control",
                    "port_channel_id_max": null,
                    "port_channel_id_min": null,
                    "position_data": null,
                    "property_set": null,
                    "role": "leaf",
                    "system_id": null,
                    "system_type": "switch",
                    "tags": null,
                    "type": "system"
                }
            },
            {
                "leaf": {
                    "deploy_mode": null,
                    "external": false,
                    "group_label": "esi_tor",
                    "hostname": "esi-tor-001-leaf2",
                    "id": "Cm_TwFyNhlx0jrVRrfY",
                    "label": "_esi_tor_001_leaf2",
                    "management_level": "full_control",
                    "port_channel_id_max": null,
                    "port_channel_id_min": null,
                    "position_data": null,
                    "property_set": null,
                    "role": "leaf",
                    "system_id": null,
                    "system_type": "switch",
                    "tags": null,
                    "type": "system"
                }
            }
        ]
    }'
  tasks:
    - name: Extract leaf IDs
      set_fact:
        leaf_ids: "{{ leaf_ids|default({})|combine({item.leaf.id: true}) }}"
      loop: "{{ count.items }}"
      when: item.leaf is defined